allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  908373ed-d738-45fd-b176-863c0d0330bb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-10-05T16:09:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5da18ddd-e379-4229-9dbe-c11babfc6fe1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-05T14:31:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dc78a212-aa47-4383-baf9-fd9307098d76 # Images
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b805a63b-0107-4c3d-afbb-7a7f22c0a7e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-05T15:48:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 13c9d98c-b2f6-4e30-9a32-64d6a42527a0 # Show Titles
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cd9845e-c8f6-47d2-82a5-fdfe5625a6ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-01T21:49:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e0206047-ceb9-43d6-a1bc-f4349a823096 # Autoplay
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 817ef9c3-f35b-42dd-9291-d618726325bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bef0c891-6a94-4713-bb2b-3df8e6ecfb1b
        userCondition: null
    thumbFieldKey: null
handle: imageCarousel
hasTitleField: true
icon: null
name: 'Image Carousel'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
