allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  72f4c879-7839-4774-91c4-40fd7c599ffc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-10-08T20:42:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b5d492a1-a643-45a0-b0ad-ea7cc3cafa3c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-08T14:59:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 72c8efb2-3aee-4b32-94c9-75882986fae0 # Review Array
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec981b99-dc88-487e-b16b-dcc5d2b927f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b875ac01-99c1-447e-b1e7-1198ac1bfb58
        userCondition: null
    thumbFieldKey: null
handle: reviewSection
hasTitleField: true
icon: null
name: 'Review Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
