allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  6bb5c75e-49bc-464a-b605-e0d9db102109:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-10-08T13:53:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dde9cf0b-6da1-4b08-87cf-008ec42a3adb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 559a359c-a4a3-470c-b4f9-e92a39d13223
        userCondition: null
    thumbFieldKey: null
handle: reviews
hasTitleField: true
icon: null
name: Reviews
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
