color: yellow
description: null
fieldLayouts:
  a726fa5c-bfd8-497e-aa4c-863d5222b09a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-28T16:27:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7b76f54c-fe7e-43d5-8df2-429312b98a6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-28T16:29:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e9b0822-f59b-476d-8610-ab0441086c64 # Single Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da8e99e2-96d1-41f7-9852-a8767d41ae5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a00a0ff1-eacc-4df2-a0fc-86c2eb6a84a3
        userCondition: null
handle: singleVideo
hasTitleField: true
icon: video
name: 'Single Video'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
