allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  512bd0f5-f49d-4367-b801-c433562191d2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-10-01T15:16:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b9620c99-e318-422f-b903-3dd5c3cab804 # Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 492b3827-aab6-4590-a0fd-a6217270ed60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-01T15:16:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fb47bc78-f6d4-418d-858a-09cad811e20d # Caption Arrow
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 635343c1-373e-441a-a87f-21a97ecbcca6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-01T15:16:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f0b7c753-cd82-46b4-a198-69bd91ad1b26 # Caption
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe482ab9-65e0-4159-868f-01905f8fc261
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d22da375-aa9f-45bf-bdba-90c91a0b2f9a
        userCondition: null
    thumbFieldKey: null
handle: singleImage
hasTitleField: false
icon: null
name: 'Single Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
