allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9ed052ed-84ed-42a8-96ba-200415997bda:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-30T19:11:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c47ba1f4-ccf8-4e41-a199-81ba3c03d041 # Body
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10cbd807-931f-4292-9d67-6ac0af19da9f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a392f87-1041-4788-bf15-bb719aa22d96
        userCondition: null
    thumbFieldKey: null
handle: textBlock
hasTitleField: false
icon: null
name: 'Text Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
