allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9ed052ed-84ed-42a8-96ba-200415997bda:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-30T19:11:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c47ba1f4-ccf8-4e41-a199-81ba3c03d041 # Body
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10cbd807-931f-4292-9d67-6ac0af19da9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-07T15:46:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f90ae485-5d95-4c51-bc72-c60df0d3b2c7 # Prose Margins
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fab6179c-8247-4117-a3f3-534d553f7a7e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-10-09T14:47:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dc290bf2-04cb-4e87-ab8f-7da321b63c10 # List Columns
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26a04d70-6dbf-40c0-bf22-c7873ee49a2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a392f87-1041-4788-bf15-bb719aa22d96
        userCondition: null
    thumbFieldKey: null
handle: textBlock
hasTitleField: false
icon: null
name: 'Text Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
