isPublic: false
name: 'General - Svelte'
scope:
  - 'sites.465e8e05-dfe1-48d5-b118-10cbe924facb:read' # stockyards_ag_experience
  - 'sections.34c2d3a9-93f5-4d47-9ca6-152a36cfcd2f:read' # Blog
  - 'sections.b889fd48-564d-4cbb-b469-fc6ca4288561:read' # Blog Posts
  - 'sections.c0ecf01e-6e64-4464-af70-7236f1c1f0f7:read' # Pages
  - 'nestedentryfields.fd66754a-765a-488d-b730-a66067c0921b:read' # Rich Text
  - 'nestedentryfields.68dd303d-90e5-40b0-bce7-c0069a17ad01:read' # Rich Text (50 word limit)
  - 'nestedentryfields.1bf4ff66-ff1c-41ae-a029-697a1c6d8b8d:read' # Accordion Fields
  - 'nestedentryfields.5ffdcb28-ff82-4961-94fd-2bf885d21e11:read' # Alert Fields
  - 'nestedentryfields.41b72d76-53a5-4ce0-a968-96e72740dc36:read' # Card Fields
  - 'nestedentryfields.f1830310-353b-4af7-a4e3-48dd1df6b8b3:read' # Content Blocks
  - 'nestedentryfields.70b3a49b-74b2-4178-b789-79e06e724ffc:read' # Fact Fields
  - 'nestedentryfields.6ec7e276-7e29-49f7-8f38-66c54284cb8e:read' # Image Card Fields
  - 'nestedentryfields.742bde2f-c58c-4bbd-a64c-9c31c229dec6:read' # Image Gallery Matrix
  - 'nestedentryfields.94c492e6-2585-46cd-b5f7-277f35023321:read' # Single Image
  - 'nestedentryfields.74e5a566-f44f-4607-8989-63304848426f:read' # Testimonial Matrix
  - 'volumes.5510aacf-c9c9-4654-83e8-f88a1ee226cb:read' # Images
  - 'volumes.fa0a59fb-e21a-41cb-a502-55d8a46dda8d:read' # Asset Embeds
  - 'globalsets.2e67e011-de0d-4211-947c-b38000dbbe04:read' # Site Settings
  - 'globalsets.4f4578d4-b6f9-48f4-8f4a-11159a0c1d71:read' # Colors
  - 'formieForms.all:read'
  - 'formieSubmissions.all:read'
  - 'navigationNavs.ebe71c90-a7ee-49f4-8b74-c44b42e3aa1b:read' # default
  - 'seomatic.all:read'
  - 'formieSubmissions.all:edit'
  - 'formieSubmissions.all:create'
