columnSuffix: null
handle: columns
instructions: null
name: Columns
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 2a7acaa3-ed4b-4e8f-8e2c-8212438f3f1b # Text Block
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - b759ecb7-f2a4-472d-abc9-c88bdac0d9e3 # Single Image
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 6e9c1b06-fb8c-49c3-bdfc-a3bf1d070aec # Card
        -
          - group
          - General
  includeTableView: false
  maxEntries: 2
  minEntries: 2
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
