columnSuffix: null
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - cb84b102-9d2a-44d7-9dd4-ff477f0d8e56 # Accordion Block
    -
      __assoc__:
        -
          - uid
          - a3b70076-a07c-4e65-87eb-c5052465d0d8 # Blog Preview Block
    -
      __assoc__:
        -
          - uid
          - 9ce8173b-bc33-4d6b-ab58-bb6fac274a4f # Form Block
    -
      __assoc__:
        -
          - uid
          - 721054c3-0bf9-4471-9b23-19a86645b4ae # Hero Block
    -
      __assoc__:
        -
          - uid
          - 3080309c-cc07-4af0-aef6-94a96f235885 # Media Block
    -
      __assoc__:
        -
          - uid
          - b1cff360-784e-4a8e-bf27-2683495ff975 # Rich Text Block
    -
      __assoc__:
        -
          - uid
          - 182cab13-62e2-4514-a1d4-87095afb5f85 # Single Image Block
    -
      __assoc__:
        -
          - uid
          - e5c5b6b2-10da-4a2c-9956-03bf23a54b18 # Single Video
    -
      __assoc__:
        -
          - uid
          - 9709673b-10c4-4af1-a65f-b1accebadef6 # Spacer
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
