columnSuffix: null
handle: listColumns
instructions: 'Splits bullets lists into columns.'
name: 'List Columns'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - One
        -
          - value
          - '1'
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Two
        -
          - value
          - '2'
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Three
        -
          - value
          - '3'
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
