fieldLayouts:
  39cc4117-3110-4ef9-bed7-4380c689b635:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-29T14:09:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 05a4db89-cb3f-4d2c-b5fc-2b9217f52f32 # Stockyards Logo
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3be63ce0-cd93-43f7-b826-d7297350359e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a15b1b78-5115-4596-bff9-5102427117cc
        userCondition: null
    thumbFieldKey: null
handle: siteSettings
name: 'Site Settings'
sortOrder: 1
