defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5c8911be-cceb-470a-8a6e-0c9ead9c2142 # Standard Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: 'http://localhost:5173/{slug}'
propagationMethod: all
siteSettings:
  465e8e05-dfe1-48d5-b118-10cbe924facb: # stockyards_ag_experience
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 88501142-7675-4d15-8048-c5795d3ab96d
type: structure
